# This workflow automatically posts a guidance comment on new pull requests.
# It welcomes contributors and provides a brief message to acknowledge their 
# contribution to the Optimizations ACE MC plugin.
# The workflow is triggered whenever a new pull request is opened.

name: New Pull Request Guidance

on:
  pull_request_target:
    types: [opened]

jobs:
  guide:
    runs-on: ubuntu-latest
    # Explicitly define permissions required by the job
    permissions:
      pull-requests: write
    steps:
      - name: Post guidance comment on new PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Thanks for contributing to Optimizations ACE MC! 🎉

            **Before we review:**
            - [ ] Have you tested your changes with WordPress 6.5+?
            - [ ] Are your changes compatible with PHP 7.4+?
            - [ ] Have you followed WordPress coding standards?
            - [ ] Did you update the CHANGELOG.md if needed?
            
            **Security Reminder:**
            This plugin can handle sensitive site configuration information, so please ensure:
            - All user inputs are properly sanitized
            - All outputs are properly escaped
            - No security vulnerabilities are introduced
            
            We'll review your PR soon! 🚀